# Generated by Django 2.0.13 on 2019-04-16 13:39

import django.db.models.deletion
from django.db import migrations, models

from drc_cmis import settings


class Migration(migrations.Migration):

    dependencies = [
        # ('datamodel', '0035_auto_20190416_1339'),
        ("drc_cmis", "0001_initial")
    ]

    operations = [
        migrations.CreateModel(
            name="DRCCMISConnection",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cmis_object_id", models.TextField(blank=True, help_text="CMIS storage object id, internal use only")),
                (
                    "enkelvoudiginformatieobject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.ENKELVOUDIGINFORMATIEOBJECT_MODEL
                    ),
                ),
            ],
        )
    ]
