# Generated by Django 2.0.13 on 2019-04-30 10:53

import django.db.models.deletion
from django.db import migrations, models

from drc_cmis import settings


class Migration(migrations.Migration):

    dependencies = [
        ('drc_cmis', '0002_drccmisconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drccmisconnection',
            name='enkelvoudiginformatieobject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cmisstorage', to=settings.ENKELVOUDIGINFORMATIEOBJECT_MODEL),
        ),
    ]
