# Generated by Django 2.0.13 on 2019-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drc_cmis', '0003_auto_20190430_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMISConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_url', models.URLField(default='http://localhost:8082/alfresco/cmisatom')),
                ('client_user', models.CharField(default='admin', max_length=200)),
                ('client_password', models.CharField(default='admin', max_length=200)),
                ('sender_property', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'CMIS Configuration',
            },
        ),
    ]
